#requires -Version 7.2
$ErrorActionPreference = 'Stop'
$project = Split-Path $PSScriptRoot -Parent
$testRoot = Join-Path ([IO.Path]::GetTempPath()) ('drive-snapshots-wiztree-' + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $testRoot | Out-Null
function Assert($condition, $message) { if (-not $condition) { throw $message } }
try {
    $raw = Join-Path $testRoot 'WizTree_fixture.csv'
    $fixture = @'
Generated by WizTree 4.32
File Name,Size,Allocated,Modified,Attributes,Files,Folders,MFTRECNO
"C:\",100,96,2026/09/12 00:00:00,0,3,2,5
"C:\Users\",80,80,2026/09/12 00:00:00,0,2,1,10
"C:\Users\Name, With Comma\",50,48,2026/09/12 00:00:00,0,1,0,11
"C:\Users\Name, With Comma\file.bin",50,48,2026/09/12 00:00:00,32,0,0,12
'@
    [IO.File]::WriteAllText($raw, $fixture, [Text.UTF8Encoding]::new($true))
    $result = & "$project/Convert-WizTreeCsv.ps1" -InputPath $raw -OutputDirectory (Join-Path $testRoot 'converted') -ViewDepth 3
    $rows = @(Import-Csv -LiteralPath $result.SnapshotCsv)
    Assert ($rows.Count -eq 3) 'Converter must keep folder rows and skip file rows'
    Assert (@($rows | Where-Object Depth -EQ '0').Count -eq 1) 'Converted CSV must contain one root'
    Assert ($rows[2].Path -eq 'C:\Users\Name, With Comma\') 'Quoted comma path must survive conversion'
    Assert ($rows[2].Depth -eq '2') 'Folder depth must be relative to the exported root'
    Assert ($rows[0].FileCount -eq '3' -and $rows[0].DescendantDirCount -eq '2' -and $rows[0].AllocatedBytes -eq '96') 'Recursive counts and allocation must be retained'
    Assert ($rows[0].Source -eq 'WizTree' -and $rows[0].Coverage -eq 'Unknown') 'Source and coverage semantics must be explicit'
    Assert ($rows[0].ViewDepth -eq '3' -and $rows[0].SnapshotScope -eq 'Full') 'Viewer metadata must be retained'
    $bad = Join-Path $testRoot 'WizTree_bad.csv'
    [IO.File]::WriteAllText($bad, "Generated by WizTree`nHeader only`n", [Text.UTF8Encoding]::new($true))
    $failed = $false
    try { & "$project/Convert-WizTreeCsv.ps1" -InputPath $bad -OutputDirectory (Join-Path $testRoot 'failed') } catch { $failed = $true }
    Assert $failed 'Malformed WizTree input must fail'
    Assert (@(Get-ChildItem (Join-Path $testRoot 'failed') -Force -ErrorAction SilentlyContinue).Count -eq 0) 'Failed conversion must not leave temporary output'
    Write-Output 'PASS: WizTree CSV streaming conversion and schema semantics'
} finally {
    $resolved = [IO.Path]::GetFullPath($testRoot)
    $tempPrefix = [IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar
    if ($resolved.StartsWith($tempPrefix) -and (Split-Path $resolved -Leaf).StartsWith('drive-snapshots-wiztree-')) {
        Remove-Item -LiteralPath $resolved -Recurse -Force
    }
}
