'use strict';
const $ = id => document.getElementById(id);
let snapshots = JSON.parse($('snapshot-data').textContent), selected = '', timer;
const fmt = n => {const sign=n<0?'−':'';n=Math.abs(n);let i=0;while(n>=1024&&i<4){n/=1024;i++;}return sign+n.toLocaleString('en',{maximumFractionDigits:1})+' '+['B','KiB','MiB','GiB','TiB'][i];};
const name = p => p.replace(/[\\/]$/,'').split(/[\\/]/).pop() || p;
const key = p => /^[a-z]:|^\\\\/i.test(p) ? p.toLowerCase().replace(/\\/g,'/').replace(/\/$/,'') : p.replace(/\/$/,'');
const parent = p => key(p).replace(/\/[^/]*$/,'');
function parseCSV(text) {
  const rows=[];let row=[],field='',quoted=false;
  text=text.replace(/^\uFEFF/,'');
  for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(Boolean))rows.push(row);row=[];field='';}else field+=c;}
  if(quoted)throw Error('Unclosed CSV quote');row.push(field);if(row.some(Boolean))rows.push(row);
  const headers=rows.shift()||[];for(const h of ['Path','Depth','SizeBytes','FileCount'])if(!headers.includes(h))throw Error('Missing column: '+h);
  const seen=new Set();return rows.map(r=>{if(r.length!==headers.length)throw Error('Invalid CSV column count');const o=Object.fromEntries(headers.map((h,i)=>[h,r[i]]));for(const h of ['Depth','SizeBytes','FileCount','Unreadable','Reparse','Incomplete']){o[h]=Number(o[h]||0);if(!Number.isSafeInteger(o[h])||o[h]<0)throw Error('Invalid '+h);}if(!o.Path||seen.has(key(o.Path)))throw Error('Empty or duplicate path');seen.add(key(o.Path));return o;});
}
function prepare(s){s.rows=s.rows.map(r=>({...r,Depth:Number(r.Depth),SizeBytes:Number(r.SizeBytes),FileCount:Number(r.FileCount),Unreadable:Number(r.Unreadable||0),Incomplete:Number(r.Incomplete||0),Reparse:Number(r.Reparse||0)}));s.root=s.rows.find(r=>r.Depth===0);if(!s.root||s.rows.filter(r=>r.Depth===0).length!==1)throw Error('Each CSV must contain exactly one depth-0 root');s.depth=s.rows.reduce((n,r)=>Math.max(n,r.Depth),0);s.index=new Map(s.rows.map(r=>[key(r.Path),r]));s.children=new Map();for(const r of s.rows){if(r.Depth===0)continue;const p=parent(r.Path);if(!s.children.has(p))s.children.set(p,[]);s.children.get(p).push(r);}return s;}
function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
function init(){snapshots.forEach(prepare);snapshots.sort((a,b)=>a.label.localeCompare(b.label));$('current').replaceChildren(...snapshots.map((s,i)=>option(i,s.label)));$('baseline').replaceChildren(option('','No comparison'),...snapshots.map((s,i)=>option(i,s.label)));$('current').value=String(snapshots.length-1);$('baseline').value=snapshots.length>1?String(snapshots.length-2):'';selected='';render();}
function render(){
  if(!snapshots.length)return;
  const s=snapshots[Number($('current').value)], b=$('baseline').value===''?null:snapshots[Number($('baseline').value)];
  const compatible=b&&key(s.root.Path)===key(b.root.Path)&&s.depth===b.depth;
  const incomplete=s.rows.some(r=>r.Incomplete||r.Unreadable)||(compatible&&b.rows.some(r=>r.Incomplete||r.Unreadable));
  $('message').textContent=(s.synthetic?'SYNTHETIC DEMO · ':'')+(b&&!compatible?'Comparison disabled: choose the same root and reported depth.':incomplete?'Partial coverage: sizes are lower bounds; differences may reflect unreadable folders.':'Files stay local. History follows filename order; choose a baseline to explore changes.');
  $('total').textContent=fmt(s.root.SizeBytes);$('count').textContent=s.root.FileCount.toLocaleString();$('delta').textContent=compatible?((s.root.SizeBytes>=b.root.SizeBytes?'+':'')+fmt(s.root.SizeBytes-b.root.SizeBytes)):'—';$('coverage').textContent=incomplete?'Partial':'No errors flagged';
  if(!selected||!s.index.has(selected))selected=key(s.root.Path);
  const current=s.index.get(selected);$('folder').textContent=current.Path;$('date').textContent=`${Number($('current').value)+1} / ${snapshots.length} snapshots`;
  const query=$('search').value.toLowerCase();const fragment=document.createDocumentFragment();
  // Cap the rendered list; the map still has access to the complete snapshot.
  const visible=s.rows.filter(r=>r.Path.toLowerCase().includes(query)).sort((a,b)=>key(a.Path).localeCompare(key(b.Path))).slice(0,1500);
  for(const r of visible){const button=document.createElement('button');button.className='tree-row'+(key(r.Path)===selected?' active':'');button.style.paddingLeft=(10+Math.min(r.Depth,10)*12)+'px';button.textContent=(r.Reparse?'↗ ':'▸ ')+name(r.Path)+' · '+fmt(r.SizeBytes);button.title=r.Path;button.onclick=()=>{selected=key(r.Path);render();};fragment.append(button);}
  $('tree').replaceChildren(fragment);
  const children=s.children.get(selected)||[];let tiles=children.filter(r=>r.SizeBytes>0).map(r=>({...r}));
  const rest=Math.max(0,current.SizeBytes-children.reduce((n,r)=>n+r.SizeBytes,0));if(rest)tiles.push({Path:'Direct files / unreported detail',SizeBytes:rest,detail:true});tiles.sort((a,b)=>b.SizeBytes-a.SizeBytes);
  const colors=['#b6efb0','#82c7b3','#94bfe3','#c2b0de','#e7c58e','#91afce'];$('map').replaceChildren();
  function layout(items,x,y,w,h){if(!items.length)return;if(items.length===1){const r=items[0],el=document.createElement('button');el.className='tile';el.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%;background:${colors[tiles.indexOf(r)%colors.length]}`;const title=document.createElement('b'),size=document.createElement('span');title.textContent=name(r.Path);size.textContent=fmt(r.SizeBytes);el.append(title,size);el.title=r.Path+' — '+fmt(r.SizeBytes);if(!r.detail)el.onclick=()=>{selected=key(r.Path);render();};else el.disabled=true;$('map').append(el);return;}const total=items.reduce((n,r)=>n+r.SizeBytes,0);let cut=1,sum=items[0].SizeBytes;while(cut<items.length-1&&sum<total/2)sum+=items[cut++].SizeBytes;const f=sum/total;if(w*$('map').clientWidth>=h*$('map').clientHeight){layout(items.slice(0,cut),x,y,w*f,h);layout(items.slice(cut),x+w*f,y,w*(1-f),h);}else{layout(items.slice(0,cut),x,y,w,h*f);layout(items.slice(cut),x,y+h*f,w,h*(1-f));}}
  layout(tiles,0,0,100,100);if(!tiles.length)$('map').textContent='No measured bytes in this folder.';
  $('changes').replaceChildren();
  if(compatible){const old=b.children.get(selected)||[];const paths=new Set([...children,...old].map(r=>key(r.Path)));const changes=[...paths].map(p=>{const now=s.index.get(p),before=b.index.get(p);return {path:(now||before).Path,delta:(now?.SizeBytes||0)-(before?.SizeBytes||0),status:!now?'not observed':!before?'newly observed':''};}).filter(r=>r.delta||r.status).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta));for(const c of changes.slice(0,50)){const el=document.createElement('div'),left=document.createElement('span'),right=document.createElement('span');el.className='change';left.textContent=name(c.path)+(c.status?' · '+c.status:'');right.className=c.delta>=0?'positive':'negative';right.textContent=(c.delta>=0?'+':'')+fmt(c.delta);el.append(left,right);$('changes').append(el);}if(!changes.length)$('changes').textContent='No changes in immediate child folders.';}else $('changes').textContent='Select a compatible baseline to see folder changes.';
}
$('files').onchange=async e=>{try{const batch=[];for(const f of e.target.files)batch.push(prepare({label:f.name,rows:parseCSV(await f.text())}));snapshots=batch;init();}catch(err){$('message').textContent='Import failed: '+err.message;}};
$('current').onchange=render;$('baseline').onchange=render;$('search').oninput=render;$('up').onclick=()=>{const s=snapshots[Number($('current').value)];if(s){selected=parent(selected);render();}};
$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='▶ Play history';return;}if(snapshots.length<2)return;$('play').textContent='❚❚ Pause';timer=setInterval(()=>{$('current').value=String((Number($('current').value)+1)%snapshots.length);render();},1800);};
$('export').onclick=async()=>{try{if(!snapshots.length)throw Error('Import snapshots first');const doc=document.documentElement.cloneNode(true);doc.querySelector('#snapshot-data').textContent=JSON.stringify(snapshots.map(({label,rows,synthetic})=>({label,rows,synthetic}))).replace(/</g,'\\u003c');const link=doc.querySelector('link[rel="stylesheet"]'),script=doc.querySelector('script[src]');if(link){const style=document.createElement('style');style.textContent=await (await fetch(link.href)).text();link.replaceWith(style);}if(script){const inline=document.createElement('script');inline.textContent=await(await fetch(script.src)).text();script.replaceWith(inline);}const blob=new Blob(['<!doctype html>\n'+doc.outerHTML],{type:'text/html'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='drive-snapshots-report.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(err){$('message').textContent='Export: '+err.message+'. For file:// use export-report.ps1, or open via a local HTTP server.';}};
init();
